# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MenuLitterarius.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(928, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.gridLayout_3 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 2)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.Manter = QtWidgets.QTabWidget(Dialog)
        self.Manter.setObjectName("Manter")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.btnFornecedores = QtWidgets.QPushButton(self.tab)
        self.btnFornecedores.setObjectName("btnFornecedores")
        self.gridLayout_4.addWidget(self.btnFornecedores, 6, 0, 1, 1)
        self.btnLivros = QtWidgets.QPushButton(self.tab)
        self.btnLivros.setObjectName("btnLivros")
        self.gridLayout_4.addWidget(self.btnLivros, 0, 0, 1, 1)
        self.btnGeneros = QtWidgets.QPushButton(self.tab)
        self.btnGeneros.setObjectName("btnGeneros")
        self.gridLayout_4.addWidget(self.btnGeneros, 2, 0, 1, 1)
        self.btnAutores = QtWidgets.QPushButton(self.tab)
        self.btnAutores.setObjectName("btnAutores")
        self.gridLayout_4.addWidget(self.btnAutores, 3, 0, 1, 1)
        self.btnClientes = QtWidgets.QPushButton(self.tab)
        self.btnClientes.setObjectName("btnClientes")
        self.gridLayout_4.addWidget(self.btnClientes, 4, 0, 1, 1)
        self.btnTransportadoras = QtWidgets.QPushButton(self.tab)
        self.btnTransportadoras.setObjectName("btnTransportadoras")
        self.gridLayout_4.addWidget(self.btnTransportadoras, 7, 0, 1, 1)
        self.btnFuncionarios = QtWidgets.QPushButton(self.tab)
        self.btnFuncionarios.setObjectName("btnFuncionarios")
        self.gridLayout_4.addWidget(self.btnFuncionarios, 5, 0, 1, 1)
        self.btnEditoras = QtWidgets.QPushButton(self.tab)
        self.btnEditoras.setObjectName("btnEditoras")
        self.gridLayout_4.addWidget(self.btnEditoras, 1, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.Manter.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 901, 511))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.btnPagamento = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnPagamento.setObjectName("btnPagamento")
        self.gridLayout.addWidget(self.btnPagamento, 1, 0, 1, 1)
        self.btnDetCompra = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnDetCompra.setObjectName("btnDetCompra")
        self.gridLayout.addWidget(self.btnDetCompra, 0, 0, 1, 1)
        self.btnDetVenda = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnDetVenda.setObjectName("btnDetVenda")
        self.gridLayout.addWidget(self.btnDetVenda, 0, 1, 1, 1)
        self.btnRecebimento = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnRecebimento.setObjectName("btnRecebimento")
        self.gridLayout.addWidget(self.btnRecebimento, 1, 1, 1, 1)
        self.Manter.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.webView = QtWebKitWidgets.QWebView(self.tab_3)
        self.webView.setGeometry(QtCore.QRect(180, 20, 711, 481))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.webView.sizePolicy().hasHeightForWidth())
        self.webView.setSizePolicy(sizePolicy)
        self.webView.setUrl(QtCore.QUrl("about:blank"))
        self.webView.setObjectName("webView")
        self.cbxRel = QtWidgets.QComboBox(self.tab_3)
        self.cbxRel.setGeometry(QtCore.QRect(10, 70, 141, 27))
        self.cbxRel.setObjectName("cbxRel")
        self.label_2 = QtWidgets.QLabel(self.tab_3)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 67, 17))
        self.label_2.setObjectName("label_2")
        self.cbxTipo = QtWidgets.QComboBox(self.tab_3)
        self.cbxTipo.setGeometry(QtCore.QRect(10, 410, 141, 27))
        self.cbxTipo.setObjectName("cbxTipo")
        self.btnGerarRel = QtWidgets.QPushButton(self.tab_3)
        self.btnGerarRel.setGeometry(QtCore.QRect(10, 440, 141, 27))
        self.btnGerarRel.setObjectName("btnGerarRel")
        self.txtRel = QtWidgets.QLineEdit(self.tab_3)
        self.txtRel.setGeometry(QtCore.QRect(10, 130, 141, 27))
        self.txtRel.setObjectName("txtRel")
        self.txtSql = QtWidgets.QLineEdit(self.tab_3)
        self.txtSql.setGeometry(QtCore.QRect(10, 180, 151, 221))
        self.txtSql.setObjectName("txtSql")
        self.label_3 = QtWidgets.QLabel(self.tab_3)
        self.label_3.setGeometry(QtCore.QRect(10, 160, 151, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab_3)
        self.label_4.setGeometry(QtCore.QRect(10, 110, 141, 17))
        self.label_4.setObjectName("label_4")
        self.Manter.addTab(self.tab_3, "")
        self.gridLayout_3.addWidget(self.Manter, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.Manter.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Litterarius"))
        self.btnFornecedores.setText(_translate("Dialog", "Fornecedores"))
        self.btnLivros.setText(_translate("Dialog", "Livros"))
        self.btnGeneros.setText(_translate("Dialog", "Generos"))
        self.btnAutores.setText(_translate("Dialog", "Autores"))
        self.btnClientes.setText(_translate("Dialog", "Clientes"))
        self.btnTransportadoras.setText(_translate("Dialog", "Transportadoras"))
        self.btnFuncionarios.setText(_translate("Dialog", "Funcionários"))
        self.btnEditoras.setText(_translate("Dialog", "Editoras"))
        self.Manter.setTabText(self.Manter.indexOf(self.tab), _translate("Dialog", "Manter"))
        self.btnPagamento.setText(_translate("Dialog", "Pagamento"))
        self.btnDetCompra.setText(_translate("Dialog", "Detalhe compra"))
        self.btnDetVenda.setText(_translate("Dialog", "Detalhe venda"))
        self.btnRecebimento.setText(_translate("Dialog", "Recebimento"))
        self.Manter.setTabText(self.Manter.indexOf(self.tab_2), _translate("Dialog", "Movimentar"))
        self.label_2.setText(_translate("Dialog", "Relatório"))
        self.btnGerarRel.setText(_translate("Dialog", "Gerar Relatório"))
        self.label_3.setText(_translate("Dialog", "Por Comando SQL"))
        self.label_4.setText(_translate("Dialog", "Por Tabela"))
        self.Manter.setTabText(self.Manter.indexOf(self.tab_3), _translate("Dialog", "Relatórios"))

from PyQt5 import QtWebKitWidgets

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

