# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Venda.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(680, 480)
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 0, 661, 481))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 7, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 12, 5, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 14, 4, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 15, 4, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 8, 0, 1, 1)
        self.lblCliente = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lblCliente.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblCliente.setObjectName("lblCliente")
        self.gridLayout.addWidget(self.lblCliente, 8, 6, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 1)
        self.lblPreco = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lblPreco.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblPreco.setObjectName("lblPreco")
        self.gridLayout_2.addWidget(self.lblPreco, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.btnCadNovo = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnCadNovo.setObjectName("btnCadNovo")
        self.gridLayout_2.addWidget(self.btnCadNovo, 1, 1, 1, 1)
        self.btnBuscarCliente = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnBuscarCliente.setObjectName("btnBuscarCliente")
        self.gridLayout_2.addWidget(self.btnBuscarCliente, 1, 0, 1, 1)
        self.cbxClientes = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.cbxClientes.setObjectName("cbxClientes")
        self.gridLayout_2.addWidget(self.cbxClientes, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 10, 5, 2, 2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 1, 5, 1, 1)
        self.tvLivros = QtWidgets.QTableView(self.gridLayoutWidget)
        self.tvLivros.setStyleSheet("alternate-background-color: rgb(200, 200, 200);")
        self.tvLivros.setObjectName("tvLivros")
        self.gridLayout.addWidget(self.tvLivros, 6, 0, 1, 7)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.txtPesquisar = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.txtPesquisar.setObjectName("txtPesquisar")
        self.horizontalLayout.addWidget(self.txtPesquisar)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 1, 1, 5)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 7, 3, 1, 1)
        self.sldQtde = QtWidgets.QSlider(self.gridLayoutWidget)
        self.sldQtde.setOrientation(QtCore.Qt.Horizontal)
        self.sldQtde.setObjectName("sldQtde")
        self.gridLayout.addWidget(self.sldQtde, 7, 1, 1, 1)
        self.btnAddLivro = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnAddLivro.setObjectName("btnAddLivro")
        self.gridLayout.addWidget(self.btnAddLivro, 7, 4, 1, 1)
        self.btnRmvLivro = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnRmvLivro.setObjectName("btnRmvLivro")
        self.gridLayout.addWidget(self.btnRmvLivro, 7, 5, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(100, 0, 331, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.rbEditora = QtWidgets.QRadioButton(self.layoutWidget)
        self.rbEditora.setObjectName("rbEditora")
        self.horizontalLayout_2.addWidget(self.rbEditora)
        self.rbAutor = QtWidgets.QRadioButton(self.layoutWidget)
        self.rbAutor.setObjectName("rbAutor")
        self.horizontalLayout_2.addWidget(self.rbAutor)
        self.rbTitulo = QtWidgets.QRadioButton(self.layoutWidget)
        self.rbTitulo.setObjectName("rbTitulo")
        self.horizontalLayout_2.addWidget(self.rbTitulo)
        self.rbGenero = QtWidgets.QRadioButton(self.layoutWidget)
        self.rbGenero.setObjectName("rbGenero")
        self.horizontalLayout_2.addWidget(self.rbGenero)
        self.gridLayout.addWidget(self.groupBox, 2, 0, 1, 7)
        self.twCarrinho = QtWidgets.QTableWidget(self.gridLayoutWidget)
        self.twCarrinho.setObjectName("twCarrinho")
        self.twCarrinho.setColumnCount(0)
        self.twCarrinho.setRowCount(0)
        self.gridLayout.addWidget(self.twCarrinho, 10, 0, 3, 5)
        self.lblInformacao = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lblInformacao.setText("")
        self.lblInformacao.setObjectName("lblInformacao")
        self.gridLayout.addWidget(self.lblInformacao, 14, 0, 1, 4)
        self.btnContinuar = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnContinuar.setObjectName("btnContinuar")
        self.gridLayout.addWidget(self.btnContinuar, 14, 6, 1, 1)
        self.sbQTDE = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.sbQTDE.setMinimum(1)
        self.sbQTDE.setMaximum(100)
        self.sbQTDE.setObjectName("sbQTDE")
        self.gridLayout.addWidget(self.sbQTDE, 7, 2, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_5.setText(_translate("Form", "Quantidade"))
        self.label.setText(_translate("Form", "Carrinho:"))
        self.lblCliente.setText(_translate("Form", "Maria Lucia"))
        self.label_2.setText(_translate("Form", "Preço Total(R$):"))
        self.lblPreco.setText(_translate("Form", "200,00"))
        self.label_4.setText(_translate("Form", "Cliente:"))
        self.btnCadNovo.setText(_translate("Form", "Cadastrar Novo"))
        self.btnBuscarCliente.setText(_translate("Form", "Buscar Cliente"))
        self.label_3.setText(_translate("Form", "Pesquisar"))
        self.btnAddLivro.setText(_translate("Form", "Adicionar Livro"))
        self.btnRmvLivro.setText(_translate("Form", "Remover Livro"))
        self.rbEditora.setText(_translate("Form", "Editora"))
        self.rbAutor.setText(_translate("Form", "Autor"))
        self.rbTitulo.setText(_translate("Form", "Titulo"))
        self.rbGenero.setText(_translate("Form", "Genero"))
        self.btnContinuar.setText(_translate("Form", "Continuar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

