# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Recebimento.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(640, 480)
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 621, 461))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.cbParcela = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.cbParcela.setObjectName("cbParcela")
        self.gridLayout_2.addWidget(self.cbParcela, 1, 5, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 1, 4, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 3, 1, 1)
        self.txtPrecoVenda = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.txtPrecoVenda.setObjectName("txtPrecoVenda")
        self.gridLayout_2.addWidget(self.txtPrecoVenda, 2, 2, 1, 1)
        self.txtCompra = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.txtCompra.setObjectName("txtCompra")
        self.gridLayout_2.addWidget(self.txtCompra, 1, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 3, 4, 1, 1)
        self.txtVlrParcela = QtWidgets.QLabel(self.gridLayoutWidget)
        self.txtVlrParcela.setObjectName("txtVlrParcela")
        self.gridLayout_2.addWidget(self.txtVlrParcela, 2, 5, 1, 1)
        self.cbxPago = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.cbxPago.setObjectName("cbxPago")
        self.gridLayout_2.addWidget(self.cbxPago, 3, 5, 1, 1)
        self.tableView_2 = QtWidgets.QTableView(self.gridLayoutWidget)
        self.tableView_2.setObjectName("tableView_2")
        self.gridLayout_2.addWidget(self.tableView_2, 5, 1, 1, 5)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 2, 4, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 1, 1, 1, 1)
        self.txtDataVenda = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.txtDataVenda.setObjectName("txtDataVenda")
        self.gridLayout_2.addWidget(self.txtDataVenda, 3, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 2, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 3, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 4, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 1, 6, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setItalic(False)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 1, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem4, 6, 1, 1, 1)
        self.lblDataPago_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setItalic(True)
        self.lblDataPago_2.setFont(font)
        self.lblDataPago_2.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.lblDataPago_2.setObjectName("lblDataPago_2")
        self.gridLayout_2.addWidget(self.lblDataPago_2, 4, 4, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem5, 0, 2, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_9.setText(_translate("Form", "Parcela"))
        self.label_10.setText(_translate("Form", "Está pago?"))
        self.txtVlrParcela.setText(_translate("Form", "TextLabel"))
        self.cbxPago.setText(_translate("Form", "CheckBox"))
        self.label_11.setText(_translate("Form", "Valor"))
        self.label_12.setText(_translate("Form", "id da venda"))
        self.label_13.setText(_translate("Form", "Preço total da venda"))
        self.label_14.setText(_translate("Form", "Data da venda realizada"))
        self.label_15.setText(_translate("Form", "Recebimento"))
        self.lblDataPago_2.setText(_translate("Form", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

